name: Run R Script Every 10 Minutes

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:        # Allows manual triggers

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'

    - name: Install R dependencies
      run: |
        R -e "install.packages(c('jsonlite', 'dplyr', 'tidyr', 'stringr', 'readr'))"

    # Log the files in the current directory to check if the script is there
    - name: List files in the directory
      run: ls -alh

    # Run the R script and capture output
    - name: Run R script
      run: |
        Rscript data-ipma.R > output.log 2> error.log
      continue-on-error: true

    # Print the logs to diagnose issues
    - name: Output R script logs
      run: |
        echo "Standard Output:"
        cat output.log
        echo "Error Output:"
        cat error.log

    # Upload the resulting CSV file as an artifact
    - name: Upload CSV artifact
      uses: actions/upload-artifact@v3
      with:
        name: IPMA_alertas.csv
        path: IPMA_alertas.csv
      continue-on-error: true  # Prevent failure if the file is not generated
