name: IPMA Alerts Processing

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  process-ipma-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("jsonlite", "dplyr", "tidyr"))'

      - name: Run IPMA Alerts Processing Script
        run: |
          Rscript -e "library(jsonlite); library(dplyr); library(tidyr); \
          url <- 'https://api.ipma.pt/open-data/forecast/warnings/warnings_www.json'; \
          data <- fromJSON(url); \
          awareness_map <- c('green' = 'Verde', 'yellow' = 'Amarelo', 'orange' = 'Laranja', 'red' = 'Vermelho', 'grey' = 'Cinzento'); \
          area_map <- c('BGC' = 'Bragança', 'ACE' = NA, 'VIS' = 'Viseu', 'EVR' = 'Évora', 'PTO' = 'Porto', 'AOC' = NA, 'GDA' = 'Guarda', 'FAR' = 'Faro', 'VRL' = 'Vila Real', 'STB' = 'Setúbal', 'STM' = 'Santarém', 'MRM' = NA, 'VCT' = 'Viana do Castelo', 'LRA' = 'Leiria', 'MCN' = NA, 'BJA' = 'Beja', 'CBO' = 'Castelo Branco', 'AVR' = 'Aveiro', 'CBR' = 'Coimbra', 'PTG' = 'Portalegre', 'MPS' = NA, 'BRG' = 'Braga', 'MCS' = NA); \
          data <- data %>% mutate(awarenessLevelID = awareness_map[awarenessLevelID], idAreaAviso = area_map[idAreaAviso]) %>% filter(!is.na(idAreaAviso)); \
          final_data <- data %>% select(idAreaAviso, awarenessTypeName, awarenessLevelID) %>% pivot_wider(names_from = awarenessTypeName, values_from = awarenessLevelID) %>% rename(local = idAreaAviso); \
          final_data[is.na(final_data)] <- 'Cinzento'; \
          write.csv(final_data, 'avisos_ipma.csv', row.names = FALSE); \
          cat('CSV gerado com sucesso como avisos_ipma.csv\\n');"

      - name: Upload CSV file
        uses: actions/upload-artifact@v3
        with:
          name: IPMA_alerts
          path: avisos_ipma.csv
